apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-test
  name: nginx-testtwo
spec:
  containers:
  - image: nginx
    name: nginx-testtwo
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
